name: CI/CD

on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write

jobs:
  build:
    name: Test and build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
            node-version: 18.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  release:
    name: Create project release
    runs-on: ubuntu-latest

    steps:
    - name: Create github release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')

  build-and-push-image:
    name: Publish docker image to Github Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
      # Setting up Docker Buildx with docker-container driver is required
      # at the moment to be able to use a subdirectory with Git context
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}