name: CI/CD

on:
    push:
        branches: [ main ]
        tags: 
          - "v*.*.*"

jobs:
    build:
        name: Test and build project
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v3

          - name: Use Node.js 18.x
            uses: actions/setup-node@v1
            with:
                node-version: 18.x
          - run: npm install
          - run: npm run build --if-present
          - run: npm test

    release:
      - name: Create project release
        runs-on: ubuntu-latest

        steps:
        - name: Create github release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
